@rootURL = http://localhost:5193

GET {{rootURL}}/weatherforecast/
Accept: application/json

###

GET {{rootURL}}/api/books
Accept: application/json

###
GET {{rootURL}}/api/books/2
Accept: application/json

###
POST {{rootURL}}/api/books
Content-Type: application/json
{
  "title": "C++ Unlocked",
  "author": "Cole",
  "yearPublished": 2021
}

###
PUT {{rootURL}}/api/books/6
Content-Type: application/json
{
  "id": 6,
  "title": "c# eBook",
  "author": "Judy",
  "yearPublished": 2045
}

###
DELETE {{rootURL}}/api/books/6